Cite: @Gutwin2010GoneBut, @Rekimoto1997PickDrop
Csl: input/resources/csl/acm-sig-proceedings.csl
Department: Technologies and Information Systems
Language: english
Month: December
Name: Lucian Andrei Farcas
Technology: Information Systems
Title: Information sources reliability. Identifying disinformation sources through the complex networks paradigm.
Subtitle: Fiabilidad de fuentes de informaci칩n. Identificaci칩n de fuentes de desinformaci칩n usando el paradigma de redes complejas.
Tutor: Alfonso Ni침o Ramos
Year: 2024
